// Author    : mat@ihep.ac.cn
// Date      : May 13, 2018 
// Descrption: It is used to draw some plots of reweighted Z->ee control samples for validation
// Inputs    : root files generated by program ../../util/re_weight.cxx 
// Outputs   : eps files store at ./plots 
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <cstdlib>
#include "Rtypes.h"
#include "TFile.h"
#include "TCanvas.h"
#include "TH1D.h"
#include "TLegend.h"
#include "TMultiGraph.h"
#include "TString.h"
#include "TStyle.h"
#include "TROOT.h"

using namespace std;
#define PRINT(x) {std::cout << #x << " = " << x << std::endl;}

void DrawDataMC(TCanvas *c, 
		bool isLogy,
		TH1D *h_data,
		TH1D *g_mc, 
		TLegend *leg,
		string leg_title,
		string x_title,
		string y_title = "Events",
		string z_title = "#frac{#font[52]{N}_{expected}}{#font[52]{N}_{observed}}",
		string leg_entry_1 = "Observed SS",
		string leg_entry_2 = "Expected SS",
		string leg_format_1 = "lep",
		string leg_format_2 = "f");
void SetStyle();
int drawPlots(bool isData);

const double VETAS[] = {0, 0.5, 1, 1.37, 1.52, 1.8, 2.0, 2.47};
const double VPTS[]  = {25, 60, 90, 130, 150, 1000};
const int NETA  = sizeof(VETAS)/sizeof(VETAS[0]) - 1;
const int NPT   = sizeof(VPTS)/sizeof(VPTS[0]) - 1;
const int SIZE  = NETA*NPT;

//double LEG_LEFT_X  = 0.65;
//double LEG_LEFT_Y  = 0.75;
double LEG_LEFT_X  = 0.75;
double LEG_LEFT_Y  = 0.80;
double LEG_RIGHT_X = 0.85;
double LEG_RIGHT_Y = 0.90;
int    LINEWIDTH   = 2;

int draw()
{
	SetStyle();
	drawPlots(true);
	drawPlots(false);

	return 0;
}

int drawPlots(bool isData)
{
	string file, output;
	if (isData)
	{
		file   = "../../run/checks_weight/data_80_100_20_20.root";
		output = "./plots/data_";
	}
	else 
	{
		file   = "../../run/checks_weight/mc_80_100_20_20.root";
		output = "./plots/mc_";
	}
	TFile *f = new TFile(file.c_str());
	if (!f->IsOpen())
	{
		cerr << "Cannot open file : " << file << endl;
		return -1;
	}
	
	struct VariableData
	{
		VariableData(string title, string name, bool islog = true)
		{
			x_title = title;
			o_name  = name;
			isLogy  = islog;
		}
		TH1D *h_data;
		TH1D *h_mc;
		string x_title;
		string o_name;
		bool isLogy;
	};
	
	vector<VariableData> hist;
	hist.clear();
	hist.push_back( VariableData("m_{ll} (GeV)",                      "mll"));
	hist.push_back( VariableData("leading #font[52]{p}_{T} (GeV)",    "pt_1"));
	hist.push_back( VariableData("subleading #font[52]{p}_{T} (GeV)", "pt_2"));
	hist.push_back( VariableData("leading #eta",                      "eta_1", false));
	hist.push_back( VariableData("subleading #eta",                   "eta_2", false));
	hist.push_back( VariableData("leading #phi",                      "phi_1", false));
	hist.push_back( VariableData("subleading #phi",                   "phi_2", false));

	cout << hist.size() << endl;

	vector<TCanvas*> c;
	for (unsigned int i = 0; i < hist.size(); i++)
	{
		TString hName = "h_" + hist[i].o_name;
		hist[i].h_mc = (TH1D*) f->Get(hName.Data());
		
		hName += "_ss";
		hist[i].h_data = (TH1D*) f->Get(hName.Data());
		
		TCanvas *tmp = new TCanvas(Form("c%d%d", isData, i), "c", 900, 900);
		TLegend *leg = new TLegend(LEG_LEFT_X, LEG_LEFT_Y, LEG_RIGHT_X, LEG_RIGHT_Y);
		c.push_back( tmp );
		string leg_title;
	   	if (isData)
		{
			leg_title = "Data";
		}
		else 
		{
			leg_title = "MC";
		}
		DrawDataMC(c[i], hist[i].isLogy, hist[i].h_data, hist[i].h_mc, leg, leg_title, hist[i].x_title);
		c[i]->SaveAs( (output + hist[i].o_name + ".eps").c_str() );
	}

	return 0;
}

void DrawDataMC(TCanvas *c, 
		bool isLogy,
		TH1D *h_data,
		TH1D *g_mc, 
		TLegend *leg,
		string leg_title,
		string x_title,
		string y_title,
		string z_title,
		string leg_entry_1,
		string leg_entry_2,
		string leg_format_1,
		string leg_format_2)
{
	char pad_name[100];
	sprintf(pad_name, "%s_%d", c->GetName(), 0);

	double size = 0.25;

	TPad *pad_1 = new TPad(pad_name,"This is pad1", 0.0, size, 1, 1);
	sprintf(pad_name, "%s_%d", c->GetName(), 1);
	TPad *pad_2 = new TPad(pad_name,"This is pad2", 0.0, 0.0, 1, size);

	pad_1->SetFillColor(0);
	pad_1->SetLeftMargin(0.23);
	pad_1->SetBottomMargin(0.17);
	pad_2->SetFillColor(0);
	pad_2->SetLeftMargin(0.23);
	pad_2->SetBottomMargin(0.17);
	pad_1->Draw();
	pad_2->Draw();
	if (isLogy)
	{
		pad_1->SetLogy();
	}
	pad_1->cd();

	h_data->SetMarkerSize(0.9);
	h_data->SetMarkerStyle(20);
	h_data->SetMarkerColor( kBlack );
	h_data->SetLineWidth(LINEWIDTH);
	h_data->SetLineColor(kBlack);
	h_data->Draw("E");
	
	double x_label_size = h_data->GetXaxis()->GetLabelSize();
	double y_label_size = h_data->GetYaxis()->GetLabelSize();
	h_data->GetXaxis()->SetTitle( x_title.c_str() );
	h_data->GetXaxis()->CenterTitle();
	h_data->GetYaxis()->SetTitle( y_title.c_str() );
	h_data->GetYaxis()->CenterTitle();
	double max = (h_data->GetMaximum() > g_mc->GetMaximum()) ? h_data->GetMaximum() : g_mc->GetMaximum();
	double min = (h_data->GetMinimum() < g_mc->GetMinimum()) ? h_data->GetMinimum() : g_mc->GetMinimum();
	if (min < 1e-5)
	{
		min = 1.;
	}
	double x_tick_length = h_data->GetXaxis()->GetTickLength();
	double font_size     = h_data->GetYaxis()->GetTitleSize();
	h_data->GetYaxis()->SetRangeUser(0.8 * min, 1.5 * max);
	g_mc->SetFillColor(kBlue);
	g_mc->SetLineColor(kBlue);
	g_mc->Draw("HIST, SAME");
	h_data->Draw("E, SAME");

	pad_1->RedrawAxis(); //force the axis redrawing

	leg->SetTextFont(42);
	//leg->SetTextSize(0.05);
	leg->SetTextSize(0.04);
	//leg->SetHeader(leg_title.c_str(), "c");
	leg->SetHeader(leg_title.c_str());
	leg->AddEntry(h_data, leg_entry_1.c_str(), leg_format_1.c_str());
	leg->AddEntry(g_mc,   leg_entry_2.c_str(), leg_format_2.c_str());
	leg->Draw();

	pad_1->Update();

	pad_2->cd();
	pad_2->SetGridy();
	TH1D *g_sys = (TH1D*)g_mc->Clone(Form("%s+%s", h_data->GetName(), g_mc->GetName()));
	g_sys->Divide(h_data);

	g_sys->SetMarkerSize(0.9);
	g_sys->SetMarkerStyle(20);
	g_sys->SetMarkerColor( kBlack );
	g_sys->SetLineWidth(LINEWIDTH);
	g_sys->SetLineColor(kBlack);
	g_sys->Draw("E");
	g_sys->GetYaxis()->SetTitle( z_title.c_str() );
	g_sys->GetYaxis()->CenterTitle();
	g_sys->GetXaxis()->SetTitle(0);
	g_sys->GetYaxis()->SetTitleSize( font_size * (1-size) / size * 0.8 );
	g_sys->GetYaxis()->SetTitleOffset( 0.4 );
	g_sys->GetYaxis()->SetRangeUser(0.0, 3.0);
	g_sys->GetYaxis()->SetNdivisions(505);
	g_sys->GetXaxis()->SetLabelSize( x_label_size * (1-size) / size );
	g_sys->GetYaxis()->SetLabelSize( y_label_size * (1-size) / size );
	g_sys->GetXaxis()->SetTickLength( x_tick_length * (1-size) / size );

	pad_2->Update();
	
}

void SetStyle()
{
	gStyle->SetOptStat(kFALSE);
	// No Canvas Border
	gStyle->SetCanvasBorderMode(0);
	gStyle->SetCanvasBorderSize(0);
	// White BG
	gStyle->SetCanvasColor(10);
	// Format for axes
	gStyle->SetLabelFont(42,"xyz");
	gStyle->SetLabelSize(0.05,"xyz");
	gStyle->SetLabelOffset(0.01,"xyz");
	gStyle->SetNdivisions(510,"xyz");
	gStyle->SetTitleFont(42,"xyz");
	gStyle->SetTitleColor(1,"xyz");
	gStyle->SetTitleSize(0.07,"xyz");
	gStyle->SetTitleOffset(1.0,"x");
	gStyle->SetTitleOffset(1.0,"y");

	//gStyle->SetTitleOffset(1.15,"xyz");
	// No pad borders
	gStyle->SetPadBorderMode(0);
	gStyle->SetPadBorderSize(0);
	// White BG
	gStyle->SetPadColor(10);
	// Margins for labels etc.
	gStyle->SetPadLeftMargin(0.15);
	gStyle->SetPadRightMargin(0.05);
	gStyle->SetPadBottomMargin(0.17);
	gStyle->SetPadTopMargin(0.05);
	// No error bars in x direction
	gStyle->SetErrorX(0);
	// Format legend
	gStyle->SetLegendBorderSize(0);
	gStyle->SetOptTitle(0);
	gStyle->SetEndErrorSize(0);
	gROOT->ForceStyle();
}
